services:
  dom:
    build: .
    volumes:
        - ./public:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - dom

# Créer un réseau dans le terminal puis:
networks:
  dom:
    external: true
    name: dom


# ---------------------------------------------------------------------------------------------------
# Dans le terminal: 
#   - 'docker network create dom'