ARG version=latest
FROM nginx:${version}

RUN apt-get update \
    && apt-get install -y nano \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs

WORKDIR /usr/share/nginx/html

COPY ./style.css .